steps:
  build:
    image: docker:git
    commands:
      - echo "Deploy step starting..."
      - docker compose build
      - docker compose -p tomthin-admin up -d
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    when:
      event: push
      branch: main
