export const queryKeys = {
  user: "user",
  users: "users",
  vendors: "vendors",
  vendor: "vendor",
  ban: "ban",
  unban: "unban",
  admin: "admin",
  admins: "admins",
  listings: "listings",
  listing: "listing",
  categories: "categories",
  approvals: "approvals",
  tomthininquiry: "tomthininquiry",
  ckinquiry: "ckinquiry",
};
