name: Automated Deployment Of Admin Panel

on:
  push:
    branches: [deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          # Add host key verification
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

          # Test connection with verbose output
          ssh -vvv -i ~/.ssh/deploy_key \
              -o IdentitiesOnly=yes \
              ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
              exit

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_timeout: 300s
          script: |
            set -ex
            cd /var/www/apps/tomthin/admin
            git pull origin dev
            npm install
            npm run build
            sudo systemctl restart nginx
