name: Deploy Admin Panel

on:
  push:
    branches: [deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/apps/tomthin/admin
            git pull origin dev
            npm install
            npm run build
            sudo systemctl restart nginx
