name: Automated Deployment Of Admin Panel

on:
  push:
    branches: [deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Environment
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          # Create known_hosts if doesn't exist
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

          # Add host key without trying to remove first
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Verify SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=yes \
              -i ~/.ssh/deploy_key \
              "${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}" \
              "echo 'SSH connection successful!'"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_timeout: 120s
          script: |
            set -ex
            cd /var/www/apps/tomthin/admin || { echo "Directory missing!"; exit 1; }
            git pull origin dev
            npm install
            npm run build
            sudo systemctl restart nginx
