name: Automated Deployment Of Admin Panel

on:
  push:
    branches: [deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          # Force compatible algorithms
          echo -e "Host *\n  HostkeyAlgorithms ssh-ed25519,ssh-rsa\n  KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256" > ~/.ssh/config
          chmod 600 ~/.ssh/config

          # Add host key
          ssh-keyscan -t ed25519,rsa ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Test Connection
        run: |
          ssh -v -o PreferredAuthentications=publickey \
              -i ~/.ssh/deploy_key \
              ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
              "echo 'Connection successful!'"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_timeout: 300s
          command_timeout: 30m
          script: |
            set -ex
            cd /var/www/apps/tomthin/admin
            git pull origin dev
            npm install
            npm run build
            sudo systemctl restart nginx
