name: Automated Deployment Of Admin Panel

on:
  push:
    branches: [dev]  # Case-sensitive! Must match your branch name.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Debug: Print branch info (verify trigger)
      - name: Check Trigger
        run: |
          echo "Branch: $GITHUB_REF"
          echo "Event: $GITHUB_EVENT_NAME"

      # SSH and deploy
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /var/www/apps/tomthin/admin
            echo "Current dir: $(pwd)"
            git remote -v  # Debug: Check Git remote
            git pull origin dev
            npm install
            npm run build
            sudo systemctl restart nginx
