name: Automated Deployment Of Admin Panel

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e  # Exit on error
            cd /var/www/apps/tomthin/admin
            echo "Setting up SSH for Git..."
            eval $(ssh-agent -s)
            echo "${{ secrets.SSH_KEY }}" | ssh-add -
            git config --global url."git@github.com:".insteadOf "https://github.com/"
            echo "Removing old build..."
            rm -rf build
            echo "Pulling latest changes..."
            git pull origin dev
            echo "Installing dependencies..."
            npm install
            echo "Building..."
            npm run build
            echo "Restarting Nginx..."
            sudo systemctl restart nginx
