name: Automated Deployment Of Admin Panel

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /var/www/apps/tomthin/admin
            # Load SSH key for Git
            eval "$(ssh-agent -s)"
            echo "${{ secrets.SSH_KEY }}" | ssh-add -
            git config --global url."git@github.com:".insteadOf "https://github.com/"
            # Pull changes
            git pull origin dev
            # Build and restart
            npm install && npm run build
            sudo systemctl restart nginx
